### ISSUE TITLE
Plugin version 1.2.1Beta crashes

### ISSUE THREAD

**Issue by intraz** [ABaumher/galaxy-integration-steam#59]
**Describe the bug**

Pressing the "Connect" button changes:
- button text to "Disconnect"
- inline plugin status to "Plugin has crashed. <ins>Retry</ins>".

Retrying doesn't help and creates the same error in the logs.

Side notes:
- disconnecting works but the title for its confirmation popup has unpopulated template text: "Disconnect {{platformName}}".
- version 1.2.0 which I upgraded from worked with no issues.
- installed using the batch file.

Thank you for this project!

**Attached logs**

**plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log:**
```
2023-12-26 17:14:13,105 - root - ERROR - Plugin exception
Traceback (most recent call last):
  File "C:\Program Files (x86)\GOG Galaxy\plugin_runner.py", line 35, in <module>
    module = importlib.import_module(filename)
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\eyalh\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\plugin.py", line 38, in <module>
    from backend_steam_network import SteamNetworkBackend
  File "C:\Users\eyalh\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\backend_steam_network.py", line 45, in <module>
    from steam_network.websocket_client import WebSocketClient
  File "C:\Users\eyalh\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\websocket_client.py", line 19, in <module>
    from .protocol_client import ProtocolClient
  File "C:\Users\eyalh\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\steam_network\protocol_client.py", line 288
    elif result == EResult.Expired
                                 ^
SyntaxError: invalid syntax
```

**GalaxyClient.log:**
```
2023-12-26 15:45:59.245 [Information][ (0)] [TID 5336][galaxy_client]: Trying to start Plugin 'pluginID/steam_ca27391f-2675-49b1-92c0-896d43afa4f8'.
2023-12-26 15:45:59.249 [Information][ (0)] [TID 5336][galaxy_client]: Plugin pluginID/steam_ca27391f-2675-49b1-92c0-896d43afa4f8 process started, waiting for 30 s for connection + 10 for capabilities + 10 for persistent storage
2023-12-26 15:45:59.249 [Information][ (0)] [TID 5336][galaxy_client]: Plugin pluginID/steam_ca27391f-2675-49b1-92c0-896d43afa4f8 starting...
2023-12-26 15:45:59.867 [Information][ (0)] [TID 5336][galaxy_client]: Plugin pluginID/steam_ca27391f-2675-49b1-92c0-896d43afa4f8 stopped, previous state Initializing
2023-12-26 15:45:59.867 [Error][ (0)] [TID 5336][galaxy_client]: Plugin - pluginID/steam_ca27391f-2675-49b1-92c0-896d43afa4f8 has crashed.
2023-12-26 15:45:59.867 [Information][ (0)] [TID 5336][galaxy_client]: Discarding problem report because 89s elapsed since last sending of Plug-In-Crashed-Error problem.
2023-12-26 15:45:59.869 [Information][ (0)] [TID 5336][galaxy_client]: Scheduling problem report plug-in_crashed_report (type external_integrations_failed).
2023-12-26 15:45:59.869 [Information][ (0)] [TID 5336][galaxy_client]: Discarding the problem report, 'plug-in_crashed_report (type external_integrations_failed)', because 89s has elapsed since sending the last report.
```

**Comment by kevinmarchant** [comment]
+1.  Same results.  New version crashes.  Reverting to old version (1.20 beta) works fine.

**Comment by ABaumher** [comment]
Yeah, that was me. I forgot a colon. Try grabbing 1.2.1 now and reinstalling it.

**Comment by ABaumher** [comment]
Bug in code, has been resolved.

**Comment by kevinmarchant** [comment]
Fixed. Doesn't crash any more.  Though first time I ran Galaxy, plugin details didn't appear in settings and no "Connect/Disconnect" buttons - just a dash under version.  Closed and reopened Galaxy - seems to be working fine now.  Will get back with more feedback if needed.

Thanks for all your efforts.

Merry Christmas and a Happy New Year to you and your family.

**Comment by intraz** [comment]
Experienced the same as @kevinmarchant described.

Thanks a lot for fixing it so quickly over the holidays.
Happy New Year!
