### ISSUE TITLE
Most of achievements not syncing

### ISSUE THREAD

**Issue by wwMRd** [ABaumher/galaxy-integration-steam#6]
Achievements are not syncing for most of games. In my case only couple of games syncing. I'm not familiar with Python but I gave it an hour and tried to investigate a bit.
It seems that games stats update times out after 10 minutes (predefined value) and function which supposed to update achievements is getting empty objects for almost all games. Games and game times seems to be up to date.

All unlocked achievements should be syncing properly.

I'm not attaching logs as I don't want to spend time to clean the information I wouldn't like to share publicly.
Here are some entries from steam log:
```
2023-05-22 07:47:05,421 - galaxy.api.plugin - INFO - Creating plugin for platform steam, version 1.0.4
2023-05-22 07:47:12,145 - galaxy.api.jsonrpc - INFO - Handling request: id=11, method=start_achievements_import, params=
2023-05-22 07:57:12,163 - steam_network.cache_proto - INFO - Timed out waiting for games cache to get ready
2023-05-22 07:57:12,163 - backend_steam_network - INFO - Finished achievements context prepare
2023-05-22 07:57:12,163 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 16 (achievements import)
2023-05-22 07:57:12,163 - galaxy.task_manager - DEBUG - Task manager plugin external: finished task 9 (start_achievements_import)
2023-05-22 07:57:12,165 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "11", "result": null}
2023-05-22 07:57:12,165 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: finished task 7 (start_achievements_import)
2023-05-22 07:57:12,165 - backend_steam_network - INFO - Asked for achievs for 43110
2023-05-22 07:57:12,165 - galaxy.api.jsonrpc - INFO - Sending notification: method=game_achievements_import_success, params={'game_id': '43110', 'unlocked_achievements': [Achievement(unlock_time=1355737994, achievement_id=None, achievement_name='First blood')]}
2023-05-22 07:57:12,166 - backend_steam_network - INFO - Asked for achievs for 35700
2023-05-22 07:57:12,166 - galaxy.api.jsonrpc - INFO - Sending notification: method=game_achievements_import_success, params={'game_id': '35700', 'unlocked_achievements': []}
```

**Comment by Amarinth** [comment]
Exact same messages here, and seems to happen every time it tries to sync achievements. Always comes up with `Timed out waiting for games cache to get ready` exactly 10 minutes after `method=start_achievements_import`, and then it imports some achievements in the last 1 second, before saying it's finished.

That would explain why some achievements do turn up eventually, but it seems to be utterly random as to when.

I can post a more complete log later, once I've had time to install the beta and leave that running for a while.

**Comment by ABaumher** [comment]
Don't have a ton of time to look into it this week, but if it's an issue of timing out after 10 minutes, i don't think there's much i can do. I have basically two options: optimize how quickly we process information to make it take less time to write to the cache, or tell gog to wait for us to finish. The latter would involve better documentation from GOG which doesn't exist, and the former is likely necessary, but also incredibly difficult/time-consuming. 

As i understand it (i didn't write any of the sync logic and haven't debugged it at all, so take with a massive grain of salt.), when we "prepare to retrieve achievements" we start getting that info and writing it to a cache. when we finish, we return somehow, and then gog calls "retrieve achievements." What's happening is gog is getting impatient and after 10 minutes, cancels the "prepare" and immediately calls "retrieve". so we give them what we have. When GOG calls tick, we update again, so it gets what we wrote to the cache since then. But it seems to call tick randomly.

**Comment by ABaumher** [comment]
i'd need to read a long log to see if we keep adding to the cache after gog finishes the prepare statement, and possibly have people with larger libraries manipulate the gog python plugin code so it logs stuff for us. unfortunately this would involve some copy-pasta. Either way, it's probably going to have to wait until the weekend.

**Comment by Amarinth** [comment]
Here's my [log](https://github.com/ABaumher/galaxy-integration-steam/files/11554617/games_cache_timeout.log) from last night, which looks like it has a decent number of these events in its.

Just let me know if you need me to tweak any files to improve the logging.

In the meantime I'm going to keep an eye on my Steam achievements, because the import process does seem to be unusually slow. To give you an idea of how slow, I've got ~150 Steam games with significant playtime & achievements, but Galaxy has only processed ~25 of them so far. I deleted the cache file when I installed the beta, so this the progress after 2 days of leaving Galaxy running in the background for most of the day.

I personally don't care much about all of the achievement stuff (just don't break my playtime stats please, lol), so I don't remember how well it worked for me in the past. However I do recall seeing plenty of complaints about this issue on the GOG forums over the years, so I wouldn't be surprised if it's always been this slow and unreliable.

**Comment by wwMRd** [comment]
I investigated a bit today. What I observed (in my case at least) - achievements are synced only for first 100 of games. Everytime same count- I tried many times today, trust me :) So what I did was sliceing set of games in 3 parts and run app separatly for every slice:
`async def run(self):
        while True:
            for job in self.job_list[89:180].copy():`
Now all my achievements are up to date.
@woj1993 idea might be good if possible. Or just somehow split it in smaller subsets and run them one after another - also if possible ofc.

**Comment by Amarinth** [comment]
Oh, that's interesting. 
So you're saying it keep re-syncing just the first 100 games unless you force it to sync the subsequent sets manually?

Some quick math tells me that's roughly in line with the numbers I recorded above. I have ~25/150 played games synced, which means on average about 1/6th of my achievements have synced, and I own ~560 games total, so 1/6th of that is not too far off 100.

**Comment by ABaumher** [comment]
It does seem odd that it takes 10 minutes to grab 100 games worth of achievements.

I honestly think the cache code sucks but it wasn't broken by the new auth so i didn't bother checking. It's also possible that we're getting that info multiple times (I've seen the same game id with achievs multiple times in a few logs), which would be inefficient as all hell. I really don't have time until the weekend to look though

**Comment by wwMRd** [comment]
No worries, take it easy. You made tremendous work which I really appreciate so I'm just trying to contribute to maybe point you in a good direction. I might find some time today to get into it little more.

**Comment by wwMRd** [comment]
@Amarinth, can I ask you a favor as you own pretty big steam library?
Exchange this file:
`<steam_plugin_catalog>\steam_network\protocol\protobuf_client.py`
with the attached one.
Run app and wait 10 min - then share your log and check achievements.

[protobuf_client.zip](https://github.com/ABaumher/galaxy-integration-steam/files/11562999/protobuf_client.zip)

**Comment by Amarinth** [comment]
That seems to have done the trick, or at least it dramatically improves the efficiency of the achievement import process! 🎉 

I could watch it filling out the missing achievement percentages for most of my played games in realtime, and it was quick too (I think if you look in the log it says `achievements_import_finished` after just 1m30s orso). 

It imported about 4 times as many achievements as it did before, and as far as I can tell they're all accounted for now. I checked the played games that are still at 0% on Steam and I just don't have any achievements for those (I probably played them modded or before achievements got added).

I have a lot of games that are just sat in my backlog, so I'm not the best test case for this. Someone who has a high number of played games with lots of achievements would be ideal to confirm how efficient the process is, but if it took 1m30s for it to process a little over 100 heavily played games for me, then hopefully it should be able to handle at least 5 times as many.

The log entries were split across two files, so I spliced them together:
[achiev_import.log](https://github.com/ABaumher/galaxy-integration-steam/files/11563358/achiev_import.log)

PS: I'm not a coder, but looking at the lines you changed, what you did was add a new function that tells it to keep re-running the job until there's nothing left to import?

**Comment by ABaumher** [comment]
I tried to look on mobile but converting it to a text file and trying to read it is... unpleasant. Technically i should be in a meeting, but they're using the wrong spelling of "board" lol. 

If it matters any, i think we do initial import of achievements in the job list array, which is exceedingly stupid. Cleaning that up may also help with making the code run better.

**Comment by ABaumher** [comment]
Checking https://github.com/ABaumher/galaxy-integration-steam/blob/master/protobuf_files/proto/steammessages_clientserver_userstats.proto, we may be able to remove an extra call we make by adding a crc_stat. If we can set the value for the play time, we halve the calls we make.

**Comment by ABaumher** [comment]
@Amarinth from what i can tell the change was a little more technical - it tries to prioritize handling packages instead of sending stat requests. In non-code speak, everything we get from Steam is in two parts: a Request (give us the info) and a Response (ok, here's that info). Our old code prioritized sending off the job requests, and never stopped to read the responses until all the requests were sent. This works fine for small libraries, but for big ones it's overwhelmingly bad. In essence, GOG hangs up on us before we can process all the responses we get. In this patch, @wwMRd is only allowing 2 jobs to go through before ensuring we take time to get responses. So even if we don't sync all of them before GOG hangs up, we still get a lot of them. It might be possible to optimize this, as asyncio has 5 active tasks by default (the rest are queued), but we do need to let regular receives for not achievement and stat code run as well. 

This is actually a really clever fix, ngl. Job List is still a hack and should be removed, but as far as bandaids on bad code, this is really up there. What i'd really like is to reimplement how we send and receive so we have a "send and wait" helper function that awaits until we get a response. This would fix this issue (and the desync thing @engiefox keeps finding) by only doing one job request at a time. again, this could be optimized by sending a few of them at the same time instead of 1 or 2.

**Comment by ABaumher** [comment]
@wwMRd there might be side effects (if we receive a message not started via the job list, it'll decrement the count), but you handle the most obvious one on the decrement by not letting it drop below 0. Honestly, i can't see how this could break anything, and it fixes a fundimental design flaw so if you open a PR i'll merge it and update the release to use it so we can hopefully consider the achievement issue solved (for now, until the whole code rework).

**Comment by engiefox** [comment]
just tried that modified file, seems to run much nicer. able to sync ~1500 achievements without issue.
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/ABaumher/galaxy-integration-steam/files/11567351/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by Gelean** [comment]
Yeah looks like this fix works. There's a 300 achievement count difference between what GoG has and what's in my Steam achievement count, but that's been an issue for awhile. Nice work!

**Comment by wwMRd** [comment]
@Amarinth I checked your logs and looks like 580 unique ids were processed - I am pretty confident that's your whole library.

@ABaumher I created this solution as fast temporary fix as I'm pretty occupied at the moment. This is far from perfection but it seems working so... I'm new to Python so I'm not really sure what can we do and what we can't.

The problem is that we are sending requests for all games (game_stats) at the same time before we start processing responses. As result GOG is cutting most of requests because we are not able to process them in time. After GOG cut the responses we are waiting until 10 min of timeout occurs (game_stats processing basicaly ends in seconds and rest of that time just waiting doing nothing lol). Then achievements retrieval (from game_stats) starts and process them for what we were able to download.

I think requests should run in parallel/background and process their own responses - run and forget, but... no idea if possible.

@ABaumher  I can open PR for current solution, just please grant me access to repo.

**Comment by woj1993** [comment]
It worked for me It started sync on 17:13:58,911 and ended on 17:18:30,858 then it started again on 18:13:45,519 and finished on 18:38:13,976 (i think the second time computer started to sleep because I left it running and found it sleeping. 
Also I found this error:
`2023-05-25 18:38:40,148 - root - ERROR - Fatal read error on pipe transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x05258CF0>
transport: <_ProactorSocketTransport fd=720>
Traceback (most recent call last):
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\proactor_events.py", line 255, in _loop_reading
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\windows_events.py", line 744, in _poll
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\windows_events.py", line 435, in finish_recv
OSError: [WinError 121] Przekroczono limit czasu semafora`

I have more that 700 games on steam.
[logs_2.zip](https://github.com/ABaumher/galaxy-integration-steam/files/11567572/logs_2.zip)

**Comment by ABaumher** [comment]
@woj1993 if google translate is any use, that error was that an internal variable timed out (a semaphore, actually. A simplified explanation is that it's used to keep stuff thread-safe, but that probably means nothing to you). Which probably happened because your computer went to sleep, so it's not an issue. 

@wwMRd i don't have the proper permissions set up to give you write acces - something about protecting master so you can't accidentally write to it, something i really should set up so i don't mess up master myself. I probably can do that this weekend (i'm actually writing this when i should be working and really need to log off, lol). In the meantime, it might be easier for you to fork my repo, overwrite protobuf client, and then do a PR that way.
Also, i have about 4 months of python experience so you're not that far behind. We can fire and forget by storing awaitables. whenever you see `variable = await <function>` we're waiting for `<function>` to finish it's async nonsense and getting the actual result. Instead, we can say `unfinished = <function>`, which gets an "awaitable" (technically a coroutine), which we can eventually `await` to get the result. If we really want fire and forget we can just discard this variable, but the safer thing to do is store all those awaitables somewhere and wait on them before finishing the program. I'm just worried doing so might cause the same issue we had before, albeit in a much cleaner way (we don't have that horrible job list array)

**Comment by woj1993** [comment]
Actually I have a degree in programming and I'm tester so I know what is a semaphore. :) I guessed that sleeping might caused this but it was worth mentioning anyway.

**Comment by ABaumher** [comment]
Fair enough, I apologize. I know some of our testers don't know any code knowledge so i try to dumb everything down.

**Comment by woj1993** [comment]
Don't apologize. I understand. Also there is no one that knows everything so I could also not known something that you do and is about programing.

**Comment by ReiTung** [comment]
not sure if it helps (and I know there is a possible patch on the way), but what I found interesting looking at my logs (I am no coder, but my brain is used to run some logic :)) is that it seems only and always the *SAME* few games have achievements imported. Looks like the import task is started around every hour, but the logs show that always the same 2 or 3 games are checked (most likely just comparing with the cache which GOG has processed already). Other way round, additional (automatically triggered, did not yet try "sync connections" but would expect it does the same) achievement sync do not touch any other game than the first few done.

**Comment by ABaumher** [comment]
It's highly possible. We do have what looks to be a really solid fix that's
incoming. I never had the achievement issue myself, but that's because my
library is small (i have like 25 games on steam, but the ones i do have
there i play a LOT of). So I'm not really a good tester. Look for the
protobuf_client.py file somewhere on this page if you want to test
yourself.

**Comment by Krynh** [comment]
211 games, nothing syncing on the first go of using the new plugin (waited over 10 minutes). Replaced the one file now and then opened Galaxy again, no achievements showing up so far.

**Comment by wwMRd** [comment]
@Krynh could you delete current steam logs, run GOG, wait full 10 minutes and upload fresh log(s)?

**Comment by Krynh** [comment]
Where are the logs kept?

**Comment by wwMRd** [comment]
@Krynh logs catalog
`%programdata%\GOG.com\Galaxy\logs`

**Comment by Krynh** [comment]
[GalaxyClient.log](https://github.com/ABaumher/galaxy-integration-steam/files/11576341/GalaxyClient.log)

**Comment by ABaumher** [comment]
For anyone who tried the new file and found it useful, don't thank me. The
credit there is all to @wwMRd. It's an extremely elegant fix and if i can
find their wishlist i might buy something for them myself lol.

That bug has existed long before i started working on this. It's been there
at least since the initial major release, lol

**Comment by TheEvilCoder42** [comment]
@wwMRd Seems to be working so far, achievements are now synced, huge thanks!

**Comment by Krynh** [comment]
I suspect the total could be even larger as it's showing xbox live achievements and galaxy ones but on many games it is still missing.

**Comment by wwMRd** [comment]
> [GalaxyClient.log](https://github.com/ABaumher/galaxy-integration-steam/files/11576341/GalaxyClient.log) Log from first time using new plugin [GalaxyClient1.log](https://github.com/ABaumher/galaxy-integration-steam/files/11576460/GalaxyClient1.log)

The correct log name starts with 'plugin-steam-'. Sorry for not being precise.
If you refer to total number of achievements on Recent tab, it my not be up to date for some time but achievements might be synced.

**Comment by Krynh** [comment]
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/ABaumher/galaxy-integration-steam/files/11576916/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.1.log](https://github.com/ABaumher/galaxy-integration-steam/files/11576921/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.1.log)

**Comment by Danyelalejandro** [comment]
Since the beggining of the integration I never could be able to sync all my huge library of achievements. I hope my logs can help everyone 
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip](https://github.com/ABaumher/galaxy-integration-steam/files/11576956/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip)

**Comment by Krynh** [comment]
It seems to be stuck on importing now, played a couple of games and unlocked some achievements but nothing's changed.

**Comment by ABaumher** [comment]
@Danyelalejandro how well is it handling achievements? for your library i'd assume you get almost none, unless you apply that patch above. Try following the instructions here: https://github.com/ABaumher/galaxy-integration-steam/issues/6#issuecomment-1562553410 and see if you get some. I don't think we'll get all of them because it won't sync in 10 minutes but it might

**Comment by wwMRd** [comment]
> From adding plugin first time: [plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.1.log](https://github.com/ABaumher/galaxy-integration-steam/files/11576921/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.1.log)

@Krynh This log is for sure from old vesion of protobuf_client.py (without fix). Are you sure you have exchanged the file or maybe this is old log?

**Comment by ABaumher** [comment]
The beginning is. the later part appears to be my code. It's possible though incredibly unlikely that i missed those error message somehow.

**Comment by ABaumher** [comment]
Also, i notice we import all the games before returning an auth of 0. This *might* be an issue for really big libraries and *maybe* explains why they crash on first connect but reconnect instantly makes the auth work. I'm going to swap over to the alpha discussion and see if this is what @engiefox has been hitting.

**Comment by ABaumher** [comment]
@Danyelalejandro can you find the ID for that one game that's not importing? if you go to steampowered.com and find that game, the url will have the app id in it. I can then search your logs to see if that id is there.

**Comment by Danyelalejandro** [comment]
> @Danyelalejandro can you find the ID for that one game that's not importing? if you go to steampowered.com and find that game, the url will have the app id in it. I can then search your logs to see if that id is there.

Yes, It is 1493750 It is recently launched, one month ago

**Comment by Krynh** [comment]
> > From adding plugin first time: [plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.1.log](https://github.com/ABaumher/galaxy-integration-steam/files/11576921/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.1.log)
> 
> @Krynh This log is for sure from old vesion of protobuf_client.py (without fix). Are you sure you have exchanged the file or maybe this is old log?

It starts before adding it and then continues on after adding it. 
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/ABaumher/galaxy-integration-steam/files/11578679/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)
here's the latest log. It's now not importing game time nor achievements

**Comment by ABaumher** [comment]
@Krynh from your logs: 
```
2023-05-26 13:56:02,067 - backend_steam_network - INFO - Asked for achievs for 221380
2023-05-26 13:56:02,067 - galaxy.api.jsonrpc - INFO - Sending notification: method=game_achievements_import_success, params={'game_id': '221380', 'unlocked_achievements': []}
```
there either aren't any that steam gives us or it's still reading from the cache and the cache is empty

**Comment by Krynh** [comment]
There are ones to show 
![image](https://github.com/ABaumher/galaxy-integration-steam/assets/18058332/1f485e84-8eec-4397-943e-b276d9f10495)
or even for halo it should by now have shown them
![image](https://github.com/ABaumher/galaxy-integration-steam/assets/18058332/e354c2d1-6d07-4bcc-b49a-7956f0680f1a)
Stellaris nothing at all.

**Comment by wwMRd** [comment]
There is a lot of different errors in the log. Some strange behaviours.
@Krynh can you restart your PC and delete all steam logs then start GOG for 10 minutes and copy log again? It is really hard to understand what is happennig in there

**Comment by Krynh** [comment]
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/ABaumher/galaxy-integration-steam/files/11579292/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by Danyelalejandro** [comment]
> > @Danyelalejandro how well is it handling achievements? for your library i'd assume you get almost none, unless you apply that patch above. Try following the instructions here: [#6 (comment)](https://github.com/ABaumher/galaxy-integration-steam/issues/6#issuecomment-1562553410) and see if you get some. I don't think we'll get all of them because it won't sync in 10 minutes but it might
> > Edit: saw your log. I'll read through that but before i start did you apply the patch or not?
> > Edit 2: Delete your logs, disconnect, then reconnect so i have a decent starting point. Your logs go back to the beginning of April and i don't feel like digging through all of that lol.
> 
> Done. Applied patch already and instructions done. I will attach logs

Finally here. Hope they can help. 0 achievements so far
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip](https://github.com/ABaumher/galaxy-integration-steam/files/11579802/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip)

**Comment by wwMRd** [comment]
@Krynh looks like 231 unique ids processed, 35 of them with unlocked achievements, total of 580 achievements processed. Unfortunately process ends with timeout so not every game was processed.

I will try to continue work on achievements import improvements in my free time. Hope I can find some :)

@Danyelalejandro your problem seems not to be connected to achievements import.
`2023-05-26 15:08:40,910 - steam_network.games_cache - WARNING - Tried to retrieve unresolved app: 1225570 for license: 424778!`
Maybe @ABaumher can say more about those warnings

**Comment by ABaumher** [comment]
@wwMRd at this point i think we're not fighting how achievements import and
instead how games are cached. I'll be honest i have no idea how that stuff
works, I've avoided it for the most part.

As for the weird warning, I've seen stuff like it and don't know why we're
getting that. It's telling us what we're not parsing what we get from steam
right. I might need to change what we log so we can see that more easily. I
also need to clean up the logs so we don't spit out so much debug info.
Evidently i needed it when i was debugging the new steps but now it's not
necessary. We can log an object using pformat

One thing we could do is import all the games before finishing
authentication. Or maybe just start that process, and let it run in the
background so it doesn't make you wait 10 minutes, idk.

**Comment by wwMRd** [comment]
For those with large libraries who still have problem with achievements missing.
You might want to try exchange stats_cache.py in this location:
`<steam_plugin_catalog>\steam_network`
Exchange this file while GOG is closed. Run GOG app and give it about half an hour.
I would appriciate clean steam log from this try.
[stats_cache.zip](https://github.com/ABaumher/galaxy-integration-steam/files/11589314/stats_cache.zip)

**Comment by Danyelalejandro** [comment]
> For those with large libraries who still have problem with achievements missing. You might want to try exchange stats_cache.py in this location: `<steam_plugin_catalog>\steam_network` Exchange this file while GOG is closed. Run GOG app and give it about half an hour. I would appriciate clean steam log from this try. [stats_cache.zip](https://github.com/ABaumher/galaxy-integration-steam/files/11589314/stats_cache.zip)

Using the file, regarding achievements, it hasn't loaded all of them (571,631) but 5,766, with recent 24 achievements of the game with ID 1493750 who appears only in recent activity but not in the library or recently played
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip](https://github.com/ABaumher/galaxy-integration-steam/files/11594134/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip)

**Comment by Krynh** [comment]
This fixed the plugin not syncing at all, it hasn't however retrieved any more of the historical achievements. I'm still missing 300 or so. 

No clean log as I didn't notice the request.

**Comment by ABaumher** [comment]
I don't think a clean log will make a difference if we're erroring where i think we are. Most of authentication will error nicely because we log everything in there. I don't think we catch any exceptions worrying too the cache and I'm afraid that's where we're blowing up. Afaik there are some weird steam appids that don't behave normally. I think these tend to be helpers that are installed alongside other apps but aren't dlc. @engiefox has a few ids pop up that make no sense, including one to the tf2 beta (regular tf2 has a different id). I'm hoping we can just ignore them, but it's going to take more verbose logging in the stats cache code. 

At the moment I'm working on the MacOS issue, and i may have secured access to a mac tomorrow so i can test out 3 potential fixes there. I'm really hoping `certifi` will fix it so i can move on from that issue. 

One other thing to consider is games you no longer own but have achievements for. For example, you can remove f2p games from your account but still have the achievements. I also recall a steamer 100%ing Resident Evil 3 in under 2 hours and refunding the game. In these cases, there's not much we can do because you don't own the game so GOG can't launch it. Also, since it's not part of your stream list

**Comment by engiefox** [comment]
Just used Walking Simulator 2020 (id 1214280) to test removing F2P games with achievements (you get one for just starting the game). Made sure the achievement showed up in GOG first, then disconnected Steam, cleared the cache, removed game from account and reconnected. Achievement no longer shows or registers on achievement count.
Here's logs from before and after removing the game:
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/ABaumher/galaxy-integration-steam/files/11644243/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/ABaumher/galaxy-integration-steam/files/11644268/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by engiefox** [comment]
As a side note: Steam itself only displays achievements for removed games if you specifically go to that games page (like in recent activity). Going to the place on my profile that displays all my achievements just displays the list of games on my account sorted by completion (Walking Sim is no longer shown). So as far as I can tell there might be no way to know what games are responsible for missing achievements if a game has been removed from the store, even if those achievements go towards the total achievement count on the profile page.

**Comment by engiefox** [comment]
I assume achieves would be preserved for games removed from Steam, since I've had games installed after they were taken down from the store and Steam will leave them alone, but proving that would be even harder(nearly impossible) than removing a F2P game from my account.

**Comment by ABaumher** [comment]
If that's the case I'm willing to chalk those up to a known issue that we can't do anything about. The goal here is to let you play games you own anywhere, with all the information that goes with it. Games you no longer own don't really fit the bill there. 

Hopefully we're not missing any other achievements. I know some massive libraries may still time out but it's good to know that might be why counts don't match when we do handle every achievement steam gives us

**Comment by ABaumher** [comment]
i'd like to close this but the issue remains that large libraries still fail. This kind of issue will hopefully be fixed by 2.0.

**Comment by DarthThong** [comment]
As far as I can tell, achievements are syncing nicely, even better than the original script, with one exception. Achievements for DLC's are not syncing correctly. The two games I've noticed this are **PC Building Simulator** and **Civilization VI**. In PC Building Simulator the IT Expansion achievements do not appear entirely, achieved or not. In Civilization VI only the achievements for the latest expansion Gathering Storm are missing, but I'm not completely sure about that. To be fair, this issue existed on the original script and it's not something introduced now.
Finally, a certain game, Portal Reloaded, a standalone mod requiring Portal 2, does not draw any info or images from Steam, just appears as an entry, although it is playable and syncs correctly. It could be a Galaxy issue and nothing to do with Steam integrator, but I had to mention it nonetheless.

**Comment by ABaumher** [comment]
For the portal mod, gog seems to pull its own assets for games so I'm not surprised if doesn't have assets for mods. Ngl I'm surprised it even appears as a launchable game. I'd expect the dlc achieves to be pulled along with the main game but it's possible the dlc is considered standalone. A little bit of context: steam doesn't give us achievements in bulk, we have to do it for every game in your library. Afaik gog only does this for games, which normally include their dlc in the achievements list. Some games might not being playing nice.

**Comment by urwrstkn8mare** [comment]
yeah same for me achievements just synced (not game time yet) but the game still hasn't been detected as installed. im guessing its just a matter of time then

**Comment by ABaumher** [comment]
Unfortunately a lot of the logic is unchanged and really not optimal for large libraries it's iterated and converted multiple times which makes it really slow. In some cases we'll take so long that gog thinks our plugin hangs or crashes and sends us a shutdown command. 

Unfortunately this and a lot of other issues are probably linked - fixing all the backend bottlenecks will fix everything all at once, but each time we find one spot it's bad that leads to like 3 others. Why is why this is set for 2.0

**Comment by samkoll** [comment]
Hey guys. I have a problem just with elden ring. I have 100% on steam, but gog show 90% only. I checked the logs (I absolutely have no idea what am I doing) and found elden ID, it imported everything succesfully. The achiv that are not showing imported also, with timestamps and everything. Any Idea Why could it not show in the app? Its like this for like half a year.

[gg.txt](https://github.com/ABaumher/galaxy-integration-steam/files/14028511/gg.txt)
