### ISSUE TITLE
Plugin crash on Mac OS (v1.2.1)

### ISSUE THREAD

**Issue by yanyshynv** [ABaumher/galaxy-integration-steam#63]
After updating from 1.2.0 to 1.2.1 version got a plugin crash after launching the GOG client. Version 1.2.0 worked nicely.

**Logs**
```
2024-04-09 23:05:08,032 - root - ERROR - Plugin exception
Traceback (most recent call last):
  File "/Applications/GOG Galaxy.app/Contents/Resources/plugin_runner.py", line 35, in <module>
    module = importlib.import_module(filename)
  File "/Applications/GOG Galaxy.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/vova/Library/Application Support/GOG.com/Galaxy/plugins/installed/steam_ca27391f-2675-49b1-92c0-896d43afa4f8/plugin.py", line 20, in <module>
    from backend_steam_network import SteamNetworkBackend
  File "/Users/vova/Library/Application Support/GOG.com/Galaxy/plugins/installed/steam_ca27391f-2675-49b1-92c0-896d43afa4f8/backend_steam_network.py", line 49, in <module>
    from steam_network.websocket_client import WebSocketClient
  File "/Users/vova/Library/Application Support/GOG.com/Galaxy/plugins/installed/steam_ca27391f-2675-49b1-92c0-896d43afa4f8/steam_network/websocket_client.py", line 23, in <module>
    from .protocol_client import ProtocolClient
  File "/Users/vova/Library/Application Support/GOG.com/Galaxy/plugins/installed/steam_ca27391f-2675-49b1-92c0-896d43afa4f8/steam_network/protocol_client.py", line 12, in <module>
    from .local_machine_cache import LocalMachineCache
ModuleNotFoundError: No module named 'steam_network.local_machine_cache'
```

**Comment by joergrech** [comment]
FYI: If someone else wan't to install it on MacOS: 1.0.8 is still working. 1.2.1beta ist crashing currently

**Comment by fenghaolw** [comment]
I am running into the same issue.

For me 1.0.8 also did not work, it did not crash but eventually threw an error and never fully sync.

```
025-06-17 09:14:48,359 - steam_network.websocket_client - ERROR - Traceback (most recent call last):
  File "/Users/fenghaolw/Library/Application Support/GOG.com/Galaxy/plugins/installed/steam_ca27391f-2675-49b1-92c0-896d43afa4f8/steam_network/websocket_client.py", line 98, in run
    await auth_task
  File "/Users/fenghaolw/Library/Application Support/GOG.com/Galaxy/plugins/installed/steam_ca27391f-2675-49b1-92c0-896d43afa4f8/steam_network/websocket_client.py", line 297, in _all_auth_calls
    ret_code = await self._protocol_client.finalize_login(self._user_info_cache.account_username, self._user_info_cache.steam_id, self._user_info_cache.refresh_token, auth_lost_handler)
  File "/Users/fenghaolw/Library/Application Support/GOG.com/Galaxy/plugins/installed/steam_ca27391f-2675-49b1-92c0-896d43afa4f8/steam_network/protocol_client.py", line 277, in finalize_login
    await self._protobuf_client.send_log_on_token_message(username, steam_id, refresh_token, self._used_server_cell_id, self._machine_id, os_value)
  File "/Users/fenghaolw/Library/Application Support/GOG.com/Galaxy/plugins/installed/steam_ca27391f-2675-49b1-92c0-896d43afa4f8/steam_network/protocol/protobuf_client.py", line 338, in send_log_on_token_message
    message.obfuscated_private_ip.v4 = await self._get_obfuscated_private_ip()
  File "/Users/fenghaolw/Library/Application Support/GOG.com/Galaxy/plugins/installed/steam_ca27391f-2675-49b1-92c0-896d43afa4f8/steam_network/protocol/protobuf_client.py", line 318, in _get_obfuscated_private_ip
    host, port = self._socket.local_address
ValueError: too many values to unpack (expected 2)
```

**Comment by fenghaolw** [comment]
So I believe the issue is IPv4 vs IPv6. The code seems to assume the IP address is v4 format, and that might be untrue for modern mac and modern internet. I dived slightly deeper and it does not seem to have room to add proper IPv6 support (I might be wrong though), and I believe the IP field is non-critical metadata and is NOT used for the main connection. The actual network connection is handling by the underlying socket which works with IPv6.

I manually patched this locally for 1.2.0 (haven't tried 1.0.8 but it might be the same issue) and it seems to work for me now.

See my local commit: https://github.com/ABaumher/galaxy-integration-steam/commit/4407778c07b6af63a23eab65f73c7be82937ace8
